"""add company metrics and sec filings tables

Revision ID: 1d0a7cafea91
Revises: 64b36aa8e27a
Create Date: 2026-06-17 18:38:19.989346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d0a7cafea91'
down_revision: Union[str, None] = '64b36aa8e27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('income_statement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('balance_sheet', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_metrics_ticker'), 'company_metrics', ['ticker'], unique=False)
    op.create_table('sec_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filed_at', sa.String(length=20), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('filing_url', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sec_filings_ticker'), 'sec_filings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sec_filings_ticker'), table_name='sec_filings')
    op.drop_table('sec_filings')
    op.drop_index(op.f('ix_company_metrics_ticker'), table_name='company_metrics')
    op.drop_table('company_metrics')
    # ### end Alembic commands ###
