"""add question to workflow runs

Revision ID: 64b36aa8e27a
Revises: 8eaf1821f692
Create Date: 2026-06-16 16:23:39.771517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b36aa8e27a'
down_revision: Union[str, None] = '8eaf1821f692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('question', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'question')
    # ### end Alembic commands ###
