"""fix workflow run status column

Revision ID: 8eaf1821f692
Revises: 2aca614628f4
Create Date: 2026-06-16 16:11:51.515032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eaf1821f692'
down_revision: Union[str, None] = '2aca614628f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('status', sa.String(length=50), nullable=False))
    op.drop_column('workflow_runs', 'question')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('question', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('workflow_runs', 'status')
    # ### end Alembic commands ###
