"""add document_chunks table

Revision ID: b57cc2255e88
Revises: 1d0a7cafea91
Create Date: 2026-06-18 16:51:19.746485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'b57cc2255e88'
down_revision: Union[str, None] = '1d0a7cafea91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
op.execute("CREATE EXTENSION IF NOT EXISTS vector")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['sec_filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_filing_id'), 'document_chunks', ['filing_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_ticker'), 'document_chunks', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_ticker'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_filing_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
